### PR TITLE
Demo page videos

### PR DESCRIPTION
**Pull request by Steve-Leke**
@lillianchou94 
These contain the updated changes.

### CODE REVIEW

**Comment by lillianchou94** [comment]
@j0n3lson @Steve-Leke Is there a way we can get this version build and deployed to a dev instance? Looks like the workflows didn't run

**Comment by Steve-Leke** [comment]
> @j0n3lson @Steve-Leke Is there a way we can get this version build and deployed to a dev instance? Looks like the workflows didn't run

Wdym?

**Comment by j0n3lson** [comment]
Does this PR replace #62? How is this one different from that PR? Is this a followup PR to that PR?

**Comment by j0n3lson** [comment]
> > @j0n3lson @Steve-Leke Is there a way we can get this version build and deployed to a dev instance? Looks like the workflows didn't run
> 
> Wdym?

It actually did run for the previous commit ([see the checks](https://github.com/mellychat/webapp/pull/81/checks?check_run_id=1744127531)). You get to that but clicking `Checks > Selecting a commit from the left` until you find a check. The check that's there is from 6 days ago -- I don't know why it doesn't run on the latest commit as well (it should).

That said, @Steve-Leke  can deploy to the dev instance easily. But I'd like to also understand how this relates to PR #62...does it replace it? If so, why not implement this one commit in that PR (since it has more comment/review history).

**Comment by Steve-Leke** [comment]
> > > @j0n3lson @Steve-Leke Is there a way we can get this version build and deployed to a dev instance? Looks like the workflows didn't run
> > 
> > 
> > Wdym?
> 
> It actually did run for the previous commit ([see the checks](https://github.com/mellychat/webapp/pull/81/checks?check_run_id=1744127531)). You get to that but clicking `Checks > Selecting a commit from the left` until you find a check. The check that's there is from 6 days ago -- I don't know why it doesn't run on the latest commit as well (it should).
> 
> That said, @Steve-Leke can deploy to the dev instance easily. But I'd like to also understand how this relates to PR #62...does it replace it? If so, why not implement this one commit in that PR (since it has more comment/review history).

This instance doesn't work very well. Coach Lilly wanted me to create this pr so she can see what I've tried and give me code. should implement to make it work. The reason why is that so far having the demo page run in multiple listeners doesn't work as well as having them run in just one.


Okay maybe it's worth updating the description with "work in progress or WIP"  and a short description as you just gave. That makes it clear that your experimenting.

**Comment by j0n3lson** [comment]
Fixed in #62

**Pull request closed without merging**
