### PR TITLE
Refactored NavBar to All Relevant Pages

### LINKED ISSUE #30: Issues with the NavBar
Somehow during the refactoring of patientSignUp.html, the navbar fails to show. 

You can't see the text nor the logo, and when you click where the text should be, it directs you to a missing page

Potential Solutions:
- Add "/" in front of the hrefs for the navbar.
- Double-check that the bootstrap code is loading in corrctly.

@Mannendri this was your pull request, so could you look into it? Let me know if you need some help!

### LINKED ISSUE #75: Extract the common main-nav section from all pages
We should definitely look into extracting the header into its own component and import it as a single element in these pages so that when we add/modify navigation items, we don't need to individually add to each page.

We have a `main-nav` section in all the pages:

https://github.com/mellychat/webapp/search?l=HTML&q=main-nav

This can be extracted into a separate file, say `nav.html` and then reimported using jQuery. See this [stackoverflow answer](https://stackoverflow.com/a/18712605)

_Originally posted by @lillianchou94 in https://github.com/mellychat/webapp/pull/62#discussion_r561320569_

### PR DESCRIPTION
**Pull request by Steve-Leke**
What's Happening:

Abstract:
A new HTML Element was created using ShadowDom.
This new element named (navBar)contains a basic version of our navBar.
This means it has no scroll wheel effect and it is not sticky.
This new element is in all pages except Demo.html and Index.html

How It Works:

The fetch method retrieves all the code from navBar.html and then runs the defineNavBar function
The defineNavBar function creates a new class that contains a constructor that attaches a shadowDom tree and to our new element and returns its shadow root.
Then Custom Elements creates the new Tag and appends the class NavBar to our new Tag.
Because of this, whenever you use the tag in a HTML page, it will run the code from navBar.html.

The review for this occurred in (https://github.com/mellychat/webapp/pull/89).

### CODE REVIEW

**Comment by j0n3lson** [comment]
Hi  @Steve-Leke, 

 A random law from [Hacker Laws repository](https://github.com/dwmkerr/hacker-laws) is a small gift to thank you for opening the PR.

-----------------------------------------------------
Cunningham's Law
-----------------------------------------------------

Cunningham's Law on Wikipedia

> The best way to get the right answer on the Internet is not to ask a question, it's to post the wrong answer.

According to Steven McGeady, Ward Cunningham advised him in the early 1980s: "The best way to get the right answer on the Internet is not to ask a question, it's to post the wrong answer." McGeady dubbed this Cunningham's law, though Cunningham denies ownership calling it a "misquote." Although originally referring to interactions on Usenet, the law has been used to describe how other online communities work (e.g., Wikipedia, Reddit, Twitter, Facebook).

See also:

- XKCD 386: "Duty Calls"

-----------------------------------------------------
         github.com/dwmkerr/hacker-laws by Dave Kerr 
-----------------------------------------------------

**Comment by Steve-Leke** [comment]
**What's Happening:**

Abstract:
A new HTML Element was created using ShadowDom. 
This new element named (navBar)contains a basic version of our navBar. 
This means it has no scroll wheel effect and it is not sticky. 
This new element is in all pages except Demo.html and Index.html

How It Works: 

1. The fetch method retrieves all the code from navBar.html and then runs the defineNavBar function
2. The defineNavBar function creates a new class that contains a constructor that activates the ShadowDom and connects it to the navBar.html.
3.  Then Custom Elements creates the new Tag and and appends the class NavBar to our new Tag.

Because of this, whenever you use the tag <navBar> in a HTML page, it will run the code from navBar.html.

**Review by j0n3lson — APPROVED** [review]
Approved. But please add a detailed description of how this change works. Think about yourself 6 months from now...think about your team mates. If I needed to add the nav bar to a new page, your comment should help me understand what I need to do and why it's done this way.

**Comment by Steve-Leke** [comment]
> Approved. But please add a detailed description of how this change works. Think about yourself 6 months from now...think about your team mates. If I needed to add the nav bar to a new page, your comment should help me understand what I need to do and why it's done this way.

@j0n3lson  I finished this. Let me know what you think!

**Comment by j0n3lson** [comment]
> **What's Happening:**
> 
> Abstract:
> A new HTML Element was created using ShadowDom. 
> This new element named (navBar)contains a basic version of our navBar. 
> This means it has no scroll wheel effect and it is not sticky. 
> This new element is in all pages except Demo.html and Index.html
> 
> How It Works: 
> 
> 1. The fetch method retrieves all the code from navBar.html and then runs the defineNavBar function
> 2. The defineNavBar function creates a new class that contains a constructor that activates the ShadowDom and connects it to the navBar.html.
> 3.  Then Custom Elements creates the new Tag and and appends the class NavBar to our new Tag.
> 
> Because of this, whenever you use the tag <navBar> in a HTML page, it will run the code from navBar.html.
>  

@Steve-Leke  excellent work here!

**Comment by Steve-Leke** [comment]
@j0n3lson Thanks!

**Pull request merged**
