### PR TITLE
DX: Adds npm script for local launches, ignore firebase debug logs

### PR DESCRIPTION
**Pull request by j0n3lson**
**NPM Scripts:**

Add a few useful npm scripts for development. The most important one is
a script that launches an instance locally, it must be run in
a container:

> npm run local

**Gitignore:**

Ignore `node_modules` which are only for development. Also ignore
firebase specific debug files.

**Developer Documentation:**

Updated  README with how to setup  a dev computer and launch a local instance.

### CODE REVIEW

**Comment by j0n3lson** [comment]
I'm moving ahead with this PR as I've been using the new commands a few days now so it seems stable/useful.

**Comment by gideoncodenext** [comment]
Sorry for the inactivity on email and github recently. I've been off of my
email enjoying break so I haven't been super up to date with the github
changes. I'll review this change now and then approve it. Thanks!

**Comment by j0n3lson** [comment]
Heya no worries.

Definitely great to chill and relax with he fam.

I actually already merged it but it doesn't hurt to read over the PR for understanding and try out the commands

Open and issue if you get stuck/have problems!

**Comment by gideoncodenext** [comment]
@j0n3lson Okay sounds good. However, I'm a little confused on how I would test out these commands. Do you have any tips on how to test out these new features?

**Comment by j0n3lson** [comment]
I also updated the README doc as well:

https://github.com/mellychat/webapp

So the old way to start a test instance was:

> firebase serve --only hosting -P dev

With this change the new way is simply:

> npm run local

And you kill a local instance like this:

> npm run killLocal

You can see in this commit that I'm adding npm scripts in `package.json` ... There's one for  `local` which just runs the firebase commands and one for `killLocal` which looks for a program listing on port 5000 (the default firebase port) and kills it.

HTH.

**Comment by gideoncodenext** [comment]
Ohhhhh that's a dope new feature. That totally helps my understanding! Thanks!!

**Pull request merged**
