### PR TITLE
Prettify the project.

### PR DESCRIPTION
**Pull request by j0n3lson**
Ran the following command:
    
> npx prettier --write
    
Note: I think we could make the source tree better here.

I had to manually remove css dependencies (like boostrap) which we 
should not prettify. This feels like there's an issue with our source tree
since I should be able to do something like the below and have it do the
right thing:
    
> npx prettier --write src/*
    
That is, to say that our tree should clearly distinguish between
dependencies and source code.

### CODE REVIEW

**Review by Mannendri — DISMISSED** [review]
Prettier definitely seems like it will be useful for our project. In thinking about distinguishing between dependencies and source code, would it be a possible solution to have dependencies in a separate sub-directory?

**Comment by j0n3lson** [comment]
> Prettier definitely seems like it will be useful for our project. In thinking about distinguishing between dependencies and source code, would it be a possible solution to have dependencies in a separate sub-directory?

I agree. I'm just not sure about what to do. The stuff in `public` _is_ the source in theory. But in practice we probably only will run prettification for the whole source tree once because we have per-commit and on-save auto formatting (with this PR). So after we merge this PR you'll get prettification for free and formatting happens as we modify our code.

So this could be me just overthinking things...interested in hearing everyone's thoughts.

**Comment by j0n3lson** [comment]
Maybe @lillianchou94  has some thoughts here? Maybe this is a non-issue?

**Comment by j0n3lson** [comment]
(pr-nagger-bot): Friendly ping. If you are a reviewer please take a look. If you are an author, please respond to comments.

**Comment by j0n3lson** [comment]
Using my magic powers to merge this change!

**Pull request merged**
